import { execFileSync, spawn } from 'node:child_process';
import { watch } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const bridgeDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const rootDir = resolve(bridgeDir, '..');
const watched = [resolve(bridgeDir, 'src'), resolve(rootDir, 'packages/client/src')];

let server;
let timer;

async function rebuild() {
  try {
    execFileSync('npm', ['--workspace', 'bridge', 'run', 'build'], { cwd: rootDir, stdio: 'inherit' });
  } catch {
    console.error('build failed, keeping previous server');
    return;
  }
  if (server) {
    const old = server;
    await new Promise((res) => { old.once('exit', res); old.kill(); }); // wait for port release before respawn
  }
  server = spawn('node', [resolve(bridgeDir, 'dist/node.js')], { cwd: bridgeDir, stdio: 'inherit', env: process.env });
}

rebuild();
for (const dir of watched) {
  watch(dir, { recursive: true }, (_event, file) => {
    if (file && /varco-client-bundle\.ts$|version\.ts$/.test(file)) return; // generated by build, ignore
    clearTimeout(timer);
    timer = setTimeout(rebuild, 150); // ponytail: 150ms debounce coalesces editor save bursts
  });
}
